import type { TemplateDefinition } from '@/types'

// Canvas reference dimensions (portrait 6.9")
// Positions and sizes use pixel values for a 1320x2868 canvas scaled to 440x956 display
const W = 440
const H = 956

export const TEMPLATES: TemplateDefinition[] = [
  // ─── Hero ─────────────────────────────────────────────────────────────────
  {
    id: 'hero',
    name: 'Hero',
    description: 'Bold headline with device centered below',
    background: {
      type: 'linear-gradient',
      angle: 135,
      stops: [
        { offset: 0, color: '#3b82f6' },
        { offset: 1, color: '#7c3aed' },
      ],
    },
    layers: [
      {
        id: 'hero-title',
        type: 'text',
        name: 'Title',
        x: 32,
        y: Math.round(H * 0.12),
        width: W - 64,
        height: 120,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 1,
        content: 'Your App,\nRedefined.',
        fontFamily: 'Inter',
        fontSize: 56,
        fontWeight: 800,
        color: '#ffffff',
        textAlign: 'center',
        lineHeight: 1.15,
        letterSpacing: -1,
        textTransform: 'none',
      },
      {
        id: 'hero-subtitle',
        type: 'text',
        name: 'Subtitle',
        x: 48,
        y: Math.round(H * 0.12) + 140,
        width: W - 96,
        height: 48,
        rotation: 0,
        opacity: 0.85,
        locked: false,
        visible: true,
        zIndex: 2,
        content: 'The fastest way to get things done.',
        fontFamily: 'Inter',
        fontSize: 20,
        fontWeight: 400,
        color: '#ffffff',
        textAlign: 'center',
        lineHeight: 1.4,
        letterSpacing: 0,
        textTransform: 'none',
      },
      {
        id: 'hero-device',
        type: 'device-frame',
        name: 'iPhone',
        x: Math.round(W * 0.15),
        y: Math.round(H * 0.44),
        width: Math.round(W * 0.7),
        height: Math.round(H * 0.5),
        rotation: 15,
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 3,
        deviceModel: 'iphone-16-pro-max',
        deviceColor: 'black-titanium',
        orientation: 'portrait',
      },
    ],
  },

  // ─── Feature ──────────────────────────────────────────────────────────────
  {
    id: 'feature',
    name: 'Feature',
    description: 'Dark background with headline and centered device',
    background: {
      type: 'solid',
      color: '#0f0f14',
    },
    layers: [
      {
        id: 'feature-headline',
        type: 'text',
        name: 'Headline',
        x: 32,
        y: Math.round(H * 0.08),
        width: W - 64,
        height: 100,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 1,
        content: 'Built for\nSpeed',
        fontFamily: 'Inter',
        fontSize: 60,
        fontWeight: 800,
        color: '#ffffff',
        textAlign: 'center',
        lineHeight: 1.1,
        letterSpacing: -1.5,
        textTransform: 'none',
      },
      {
        id: 'feature-sub',
        type: 'text',
        name: 'Subtitle',
        x: 48,
        y: Math.round(H * 0.08) + 120,
        width: W - 96,
        height: 40,
        rotation: 0,
        opacity: 0.6,
        locked: false,
        visible: true,
        zIndex: 2,
        content: 'Blazing fast performance, every time.',
        fontFamily: 'Inter',
        fontSize: 18,
        fontWeight: 400,
        color: '#ffffff',
        textAlign: 'center',
        lineHeight: 1.4,
        letterSpacing: 0,
        textTransform: 'none',
      },
      {
        id: 'feature-device',
        type: 'device-frame',
        name: 'iPhone',
        x: Math.round(W * 0.1),
        y: Math.round(H * 0.42),
        width: Math.round(W * 0.8),
        height: Math.round(H * 0.54),
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 3,
        deviceModel: 'iphone-16-pro-max',
        deviceColor: 'white-titanium',
        orientation: 'portrait',
      },
    ],
  },

  // ─── Side-by-side ─────────────────────────────────────────────────────────
  {
    id: 'side-by-side',
    name: 'Side by Side',
    description: 'Two devices with centered headline',
    background: {
      type: 'linear-gradient',
      angle: 160,
      stops: [
        { offset: 0, color: '#f0f4ff' },
        { offset: 1, color: '#e8d5f5' },
      ],
    },
    layers: [
      {
        id: 'sbs-headline',
        type: 'text',
        name: 'Headline',
        x: 24,
        y: Math.round(H * 0.07),
        width: W - 48,
        height: 80,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 1,
        content: 'Designed for You',
        fontFamily: 'Inter',
        fontSize: 44,
        fontWeight: 800,
        color: '#1a1a2e',
        textAlign: 'center',
        lineHeight: 1.15,
        letterSpacing: -0.5,
        textTransform: 'none',
      },
      {
        id: 'sbs-sub',
        type: 'text',
        name: 'Subtitle',
        x: 40,
        y: Math.round(H * 0.07) + 96,
        width: W - 80,
        height: 36,
        rotation: 0,
        opacity: 0.7,
        locked: false,
        visible: true,
        zIndex: 2,
        content: 'Works seamlessly on all your devices.',
        fontFamily: 'Inter',
        fontSize: 17,
        fontWeight: 400,
        color: '#1a1a2e',
        textAlign: 'center',
        lineHeight: 1.4,
        letterSpacing: 0,
        textTransform: 'none',
      },
      {
        id: 'sbs-device-left',
        type: 'device-frame',
        name: 'iPhone Left',
        x: Math.round(W * 0.02),
        y: Math.round(H * 0.38),
        width: Math.round(W * 0.46),
        height: Math.round(H * 0.55),
        rotation: -8,
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 3,
        deviceModel: 'iphone-16-pro',
        deviceColor: 'natural-titanium',
        orientation: 'portrait',
      },
      {
        id: 'sbs-device-right',
        type: 'device-frame',
        name: 'iPhone Right',
        x: Math.round(W * 0.52),
        y: Math.round(H * 0.38),
        width: Math.round(W * 0.46),
        height: Math.round(H * 0.55),
        rotation: 8,
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 4,
        deviceModel: 'iphone-16-pro',
        deviceColor: 'desert-titanium',
        orientation: 'portrait',
      },
    ],
  },

  // ─── Full Bleed ───────────────────────────────────────────────────────────
  {
    id: 'full-bleed',
    name: 'Full Bleed',
    description: 'Full background with gradient text overlay at bottom',
    background: {
      type: 'solid',
      color: '#1a1a2e',
    },
    layers: [
      {
        id: 'fb-overlay',
        type: 'shape',
        name: 'Gradient Overlay',
        x: 0,
        y: Math.round(H * 0.55),
        width: W,
        height: Math.round(H * 0.45),
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 1,
        shapeType: 'rectangle',
        fill: {
          type: 'linear',
          angle: 180,
          stops: [
            { offset: 0, color: 'rgba(0,0,0,0)' },
            { offset: 1, color: 'rgba(0,0,0,0.85)' },
          ],
        },
      },
      {
        id: 'fb-title',
        type: 'text',
        name: 'Title',
        x: 32,
        y: Math.round(H * 0.72),
        width: W - 64,
        height: 96,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 2,
        content: 'Experience\nthe Difference',
        fontFamily: 'Inter',
        fontSize: 42,
        fontWeight: 800,
        color: '#ffffff',
        textAlign: 'left',
        lineHeight: 1.15,
        letterSpacing: -0.5,
        textTransform: 'none',
      },
      {
        id: 'fb-sub',
        type: 'text',
        name: 'Subtitle',
        x: 32,
        y: Math.round(H * 0.72) + 108,
        width: W - 64,
        height: 36,
        rotation: 0,
        opacity: 0.75,
        locked: false,
        visible: true,
        zIndex: 3,
        content: 'Download now and see for yourself.',
        fontFamily: 'Inter',
        fontSize: 18,
        fontWeight: 400,
        color: '#ffffff',
        textAlign: 'left',
        lineHeight: 1.4,
        letterSpacing: 0,
        textTransform: 'none',
      },
    ],
  },

  // ─── Minimal ──────────────────────────────────────────────────────────────
  {
    id: 'minimal',
    name: 'Minimal',
    description: 'Clean layout with large text left and device right',
    background: {
      type: 'solid',
      color: '#f8f8f8',
    },
    layers: [
      {
        id: 'min-label',
        type: 'text',
        name: 'Label',
        x: 28,
        y: Math.round(H * 0.18),
        width: Math.round(W * 0.55),
        height: 24,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 1,
        content: 'PRODUCTIVITY',
        fontFamily: 'Inter',
        fontSize: 12,
        fontWeight: 700,
        color: '#6366f1',
        textAlign: 'left',
        lineHeight: 1,
        letterSpacing: 2.5,
        textTransform: 'uppercase',
      },
      {
        id: 'min-title',
        type: 'text',
        name: 'Title',
        x: 28,
        y: Math.round(H * 0.18) + 34,
        width: Math.round(W * 0.57),
        height: 200,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 2,
        content: 'Do More,\nStress Less.',
        fontFamily: 'Inter',
        fontSize: 52,
        fontWeight: 800,
        color: '#111111',
        textAlign: 'left',
        lineHeight: 1.1,
        letterSpacing: -1,
        textTransform: 'none',
      },
      {
        id: 'min-device',
        type: 'device-frame',
        name: 'iPhone',
        x: Math.round(W * 0.48),
        y: Math.round(H * 0.1),
        width: Math.round(W * 0.5),
        height: Math.round(H * 0.58),
        rotation: 4,
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 3,
        deviceModel: 'iphone-16-pro-max',
        deviceColor: 'black-titanium',
        orientation: 'portrait',
      },
    ],
  },
]
